#!/bin/bash

set -euo pipefail

src=${1?}
shift

module=$(basename "$src" .elm)
output=./elm-stuff/${module}.js

npx elm make ${ELM_ARGS:-} --output="$output" "$src"

node -e "(w=>console.warn=(a,...b)=>/^Compiled in DEV/.test(a)||w(a,...b))(console.warn);
         require('${output}').Elm.${module}
           .init({flags:process.argv.slice(1)})
           .ports.jsonConsole.subscribe(console.log)" "$@"
