#!/bin/bash

set -euo pipefail

src=${1?}
module=$(basename "$src" .elm)
output=${module}.js

npx elm make --output="${module}.js" "$src"

echo 'this.Elm.'${module}'.init(JSON.stringify(process.argv[2])).ports.jsonConsole.subscribe(console.log);' >> "$output"

node "$output"
